controllers:
    resource: ../src/Controllers/
    type: attribute
    prefix: /api

api_users_index:
    path: /api/users
    controller: App\Controllers\UserController::index
    methods: [GET]

api_user_show:
    path: /api/users/{id}
    controller: App\Controllers\UserController::show
    methods: [GET]

api_user_create:
    path: /api/users
    controller: App\Controllers\UserController::create
    methods: [POST]

api_user_update:
    path: /api/users/{id}
    controller: App\Controllers\UserController::update
    methods: [PUT]

api_user_delete:
    path: /api/users/{id}
    controller: App\Controllers\UserController::delete
    methods: [DELETE]

api_routes:
    resource: ../src/Controllers/
    type: attribute
    prefix: /api